### ISSUE TITLE
dependencies versions

### ISSUE THREAD

**Issue by hariszaf** [ModelSEED/ModelSEEDpy#107]
Hi there. 

Could you please add in the `requirements` file the versions of the dependencies? 
I am running on some issues that come up from example a conflict with `scikit-learn`.

Here is how it behaves:

```
genome_class = genome_classifier.classify(genome)
```
returned the following error:
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [4], line 2
      1 from modelseedpy.helpers import get_classifier
----> 2 genome_classifier = get_classifier('knn_filter')
      3 genome_class = genome_classifier.classify(genome)
      4 print(genome_class)

File ~/.local/lib/python3.10/site-packages/modelseedpy/helpers.py:46, in get_classifier(classifier_id)
     44 print(cls_features)
     45 with open(cls_pickle, "rb") as fh:
---> 46     model_filter = pickle.load(fh)
     47 with open(cls_features, "r") as fh:
     48     features = json.load(fh)

ModuleNotFoundError: No module named 'sklearn.neighbors._dist_metrics'
```

When I downgraded my `scikit-learn` to the `0.24.0` version it worked fine. 

However, I then tried to run 
```
genome_class = genome_classifier.classify(genome)
```
and I got this:
```
genome_class = genome_classifier.classify(genome)
Traceback (most recent call last):
  File "/home/luna.kuleuven.be/u0156635/.conda/envs/modelseed/lib/python3.9/site-packages/modelseedpy/ml/predict_phenotype.py", line 94, in create_indicator_matrix
    indicators[np.array(matching_index)] = 1
IndexError: arrays used as indices must be of integer (or boolean) type
```

I am not sure if the last error is due to a version conflict but i guess something is not installed as it should .

Thanks !

**Comment by Fxe** [comment]
Maybe you got error pages from the downloaded data files in

`/home/luna.kuleuven.be/u0156635/.conda/envs/modelseed/lib/python3.9/site-packages/modelseedpy/data/ml`

Go to that folder and clear the jsons and pickles
Check if you can access https://bioseed.mcs.anl.gov/~fliu/modelseedpy/
Run the library it should auto download the files (check if the pickles are actual pickles and not HTML page access errors)

**The latest version of modelseedpy (dev branch) requires scikit-learn 1.2.0 and python >=3.8 (you have 3.9 that should work)**

**Comment by hariszaf** [comment]
Hi @Fxe ! 
Thanks a lot for reaching back. 

Regarding, the last error I got that was my bad. 
I had a `.fna` file as genome instead of a `.faa`. 

Regarding my main question, under the path you said, I currently have 2 files:
`knn_filter_features.json`  `knn_filter.pickle`

and here is what I get from the link you sent: 
![image](https://user-images.githubusercontent.com/33932522/214689296-c9361c13-c6a9-42d1-aed5-a88cfdb5724e.png)

Should I move as you said, i.e. remove the pickles and the jsons? 
Thanks again!

**Comment by Fxe** [comment]
That is the correct page output is just to check if you can access the links, remove the download files in your `data/ml` folder and the library will attempt to redownload new files from that URL
The `knn_filter_features.json` and `knn_filter.pickle` are the old model version for scikit-learn `0.24.0` you should update modelseedpy so it downloads the `knn_ACNP_RAST_filter_01_17_2023` predictor files

**Comment by hariszaf** [comment]
Hi again @Fxe !

After cleaning everything on my side, I cloned the repo and in a conda environmnet I did as suggested but I still get the old files, even with `scikit-learn=1.2.0`

```
>>> genome_classifier = get_classifier('knn_filter')
modelseedpy.helpers - WARNING - mkdir: /home/luna.kuleuven.be/u0156635/.local/lib/python3.10/site-packages/modelseedpy//data/ml
modelseedpy.helpers - WARNING - downloading data file to: /home/luna.kuleuven.be/u0156635/.local/lib/python3.10/site-packages/modelseedpy//data/ml/knn_filter.pickle
modelseedpy.helpers - WARNING - downloading data file to: /home/luna.kuleuven.be/u0156635/.local/lib/python3.10/site-packages/modelseedpy//data/ml/knn_filter_features.json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luna.kuleuven.be/u0156635/.local/lib/python3.10/site-packages/modelseedpy/helpers.py", line 43, in get_classifier
    model_filter = pickle.load(fh)
ModuleNotFoundError: No module named 'sklearn.neighbors._dist_metrics'
>>> import sklearn
>>> sklearn.__version__
'1.2.0'

```
Do you have any idea why ? 
Is there any other way to get the new files ? 

Really appreciate your help!

**Comment by Fxe** [comment]
because `knn_filter` is the old classifier just change to the new classifier and it should work https://github.com/ModelSEED/ModelSEEDpy/blob/dev/modelseedpy/core/msbuilder.py#L665

**Comment by hariszaf** [comment]
Ok great! 
Thanks a lot for the help @Fxe !

I consider this issue closed.
