### ISSUE TITLE
Gapfilling error

### ISSUE THREAD

**Issue by freiburgermsu** [ModelSEED/ModelSEEDpy#122]
Hello!

The Gapfilling function in `MSBuilder` returns the [original, ungapfilled, model](https://github.com/ModelSEED/ModelSEEDpy/blob/dev/modelseedpy/core/msbuilder.py#L1036) instead of the gapfilled model. This seems counter-intuitive and to be a bug instead of a feature. How is the user expected to acquire the gapfilled model from a static method unless it is returned??

**Comment by Fxe** [comment]
it returns the gapfilled model new reactions are added in https://github.com/ModelSEED/ModelSEEDpy/blob/dev/modelseedpy/core/msbuilder.py#L1029 perhaps it is just the name of the parameter causes confusion

**Comment by freiburgermsu** [comment]
@Fxe Indeed, thank you for clarifying!
