### ISSUE TITLE
KBaseMediaPkg class missing 'mediacompounds' attribute

### ISSUE THREAD

**Issue by tjmoutinhocgn** [ModelSEED/ModelSEEDpy#55]
Hello, 
I ran into the following error when attempting to run the 'build_metabolic_model.ipynb' example notebook. Do you have any suggestions for fixing this issue? I didn't make any edits to your example notebook. I was able to get the function to run by commenting out lines 47-61 in 'kbasemediapkg.py', however the model output has far more reactions and metabolites than the one shown in the example output.
Thanks in advance for any help you can provide!
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <module>
----> 1 model = MSBuilder.build_metabolic_model('ecoli.core', genome, template, None, allow_all_non_grp_reactions=True, annotate_with_rast=True)
      2 model

File ~/anaconda3/envs/genre/lib/python3.10/site-packages/ModelSEEDpy-0.2.2-py3.10.egg/modelseedpy/core/msbuilder.py:616, in MSBuilder.build_metabolic_model(model_id, genome, gapfill_media, template, index, allow_all_non_grp_reactions, annotate_with_rast, gapfill_model)
    614 # Gapfilling model
    615 if gapfill_model:
--> 616     model = MSBuilder.gapfill_model(model, 'bio1', builder.template, gapfill_media)
    617 return model

File ~/anaconda3/envs/genre/lib/python3.10/site-packages/ModelSEEDpy-0.2.2-py3.10.egg/modelseedpy/core/msbuilder.py:630, in MSBuilder.gapfill_model(original_mdl, target_reaction, template, media)
    623 pkgmgr = MSPackageManager.get_pkg_mgr(model)
    624 pkgmgr.getpkg("GapfillingPkg").build_package({
    625     "default_gapfill_templates": [template],
    626     "gapfill_all_indecies_with_default_templates": 1,
    627     "minimum_obj": 0.01,
    628     "set_objective": 1
    629 })
--> 630 pkgmgr.getpkg("KBaseMediaPkg").build_package(media)
    631 #with open('Gapfilling.lp', 'w') as out:
    632 #    out.write(str(model.solver))
    633 sol = model.optimize()

File ~/anaconda3/envs/genre/lib/python3.10/site-packages/ModelSEEDpy-0.2.2-py3.10.egg/modelseedpy/fbapkg/kbasemediapkg.py:49, in KBaseMediaPkg.build_package(self, media_or_parameters, default_uptake, default_excretion)
     45         reaction.update_variable_bounds()  # FIXME: this seems unnecessary
     47 if self.parameters["media"]:
     48     # Searching for media compounds in model
---> 49     for compound in self.parameters["media"].mediacompounds:
     50         mdlcpds = self.find_model_compounds(compound.id)
     51         for mdlcpd in mdlcpds:

AttributeError: 'NewModelTemplate' object has no attribute 'mediacompounds'

**Comment by Fxe** [comment]
sorry the example was outdated the arguments got swap:
instead of:
`model = MSBuilder.build_metabolic_model('ecoli.core', genome, template, None, allow_all_non_grp_reactions=True, annotate_with_rast=True)`
should be:
`model = MSBuilder.build_metabolic_model('ecoli.core', genome, None, template, allow_all_non_grp_reactions=True, annotate_with_rast=True)`

we updated the example to a cleaner version, thanks for pointing out this issue!

**Comment by tjmoutinhocgn** [comment]
That fixed it on my end, thanks!
